services:
  db:
    image: "postgres:16.2"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/.volumes/:/var/lib/postgresql/data/